apiVersion: v1  
kind: Service  
metadata:  
  name: spring-service  
spec:  
  type: NodePort  
  selector:  
    app: spring-app  
  ports:  
    - protocol: TCP  
      port: 8089  
      targetPort: 8089  
      nodePort: 30090  # Port NodePort entre 30000-32767  
